using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data;
namespace GolfPool_Service
{
    class PicksDB
    {

        DataTable picks;

        PicksDB()
        {
            picks = new DataTable("Picks");
            picks.Columns.Add("Entrant");
            picks.Columns.Add("Golfer");
            picks.Rows.Add("Ryan Moore", "Adam Scott");
            picks.Rows.Add("Ryan Moore", "Anthony Kim");
            picks.Rows.Add("Ryan Moore", "Camilo Villegas");
            picks.Rows.Add("Ryan Moore", "Gary Woodland");
            picks.Rows.Add("Ryan Moore", "Lee Westwood");
            picks.Rows.Add("Ryan Moore", "Rickie Fowler");
            picks.Rows.Add("Ryan Moore", "Rory McIlroy");
            picks.Rows.Add("Ryan Moore", "Sergio Garcia");
            picks.Rows.Add("Ryan Moore", "Tiger Woods");
            picks.Rows.Add("Ryan Moore", "Trevor Immelman");
            picks.Rows.Add("Stuart Kingham", "Camilo Villegas");
            picks.Rows.Add("Stuart Kingham", "Chad Campbell");
            picks.Rows.Add("Stuart Kingham", "Dustin Johnson");
            picks.Rows.Add("Stuart Kingham", "Geoff Ogilvy");
            picks.Rows.Add("Stuart Kingham", "Hunter Mahan");
            picks.Rows.Add("Stuart Kingham", "Jim Furyk");
            picks.Rows.Add("Stuart Kingham", "Rickie Fowler");
            picks.Rows.Add("Stuart Kingham", "Ricky Barnes");
            picks.Rows.Add("Stuart Kingham", "Tiger Woods");
            picks.Rows.Add("Stuart Kingham", "Zach Johnson");
            picks.Rows.Add("Mike Allman", "Jim Furyk");
            picks.Rows.Add("Mike Allman", "Kevin Stadler");
            picks.Rows.Add("Mike Allman", "Lee Westwood");
            picks.Rows.Add("Mike Allman", "Luke Donald");
            picks.Rows.Add("Mike Allman", "Phil Mickelson");
            picks.Rows.Add("Mike Allman", "Rickie Fowler");
            picks.Rows.Add("Mike Allman", "Rory McIlroy");
            picks.Rows.Add("Mike Allman", "Ryo Ishikawa");
            picks.Rows.Add("Mike Allman", "Spencer Levin");
            picks.Rows.Add("Mike Allman", "Tiger Woods");
            picks.Rows.Add("Scott Platten", "Adam Scott");
            picks.Rows.Add("Scott Platten", "Dustin Johnson");
            picks.Rows.Add("Scott Platten", "Graeme McDowell");
            picks.Rows.Add("Scott Platten", "Jim Furyk");
            picks.Rows.Add("Scott Platten", "Lee Westwood");
            picks.Rows.Add("Scott Platten", "Phil Mickelson");
            picks.Rows.Add("Scott Platten", "Rory McIlroy");
            picks.Rows.Add("Scott Platten", "Sergio Garcia");
            picks.Rows.Add("Scott Platten", "Tiger Woods");
            picks.Rows.Add("Scott Platten", "Zach Johnson");
            picks.Rows.Add("Manny Marcelo", "Adam Scott");
            picks.Rows.Add("Manny Marcelo", "Ben Crane");
            picks.Rows.Add("Manny Marcelo", "Bubba Watson");
            picks.Rows.Add("Manny Marcelo", "Lucas Glover");
            picks.Rows.Add("Manny Marcelo", "Sean O'Hair");
            picks.Rows.Add("Manny Marcelo", "Steve Stricker");
            picks.Rows.Add("Manny Marcelo", "Stuart Appleby");
            picks.Rows.Add("Manny Marcelo", "Tiger Woods");
            picks.Rows.Add("Manny Marcelo", "Tim Clark");
            picks.Rows.Add("Manny Marcelo", "Zach Johnson");
            picks.Rows.Add("Tomas Holmstrom", "Ben Crane");
            picks.Rows.Add("Tomas Holmstrom", "Bo Van Pelt");
            picks.Rows.Add("Tomas Holmstrom", "Bubba Watson");
            picks.Rows.Add("Tomas Holmstrom", "Camilo Villegas");
            picks.Rows.Add("Tomas Holmstrom", "Jim Furyk");
            picks.Rows.Add("Tomas Holmstrom", "Sean O'Hair");
            picks.Rows.Add("Tomas Holmstrom", "Sergio Garcia");
            picks.Rows.Add("Tomas Holmstrom", "Steve Stricker");
            picks.Rows.Add("Tomas Holmstrom", "Tiger Woods");
            picks.Rows.Add("Tomas Holmstrom", "Zach Johnson");
            picks.Rows.Add("Bob Grant", "Bubba Watson");
            picks.Rows.Add("Bob Grant", "Chris DiMarco");
            picks.Rows.Add("Bob Grant", "Jason Day");
            picks.Rows.Add("Bob Grant", "Lucas Glover");
            picks.Rows.Add("Bob Grant", "Padraig Harrington");
            picks.Rows.Add("Bob Grant", "Rickie Fowler");
            picks.Rows.Add("Bob Grant", "Ryuji Imada");
            picks.Rows.Add("Bob Grant", "Sean O'Hair");
            picks.Rows.Add("Bob Grant", "Steve Stricker");
            picks.Rows.Add("Bob Grant", "Tiger Woods");
            picks.Rows.Add("Kevin Grant", "Adam Scott");
            picks.Rows.Add("Kevin Grant", "Bubba Watson");
            picks.Rows.Add("Kevin Grant", "Camilo Villegas");
            picks.Rows.Add("Kevin Grant", "Charl Schwartzel");
            picks.Rows.Add("Kevin Grant", "Jim Furyk");
            picks.Rows.Add("Kevin Grant", "Padraig Harrington");
            picks.Rows.Add("Kevin Grant", "Phil Mickelson");
            picks.Rows.Add("Kevin Grant", "Sergio Garcia");
            picks.Rows.Add("Kevin Grant", "Stuart Appleby");
            picks.Rows.Add("Kevin Grant", "Tiger Woods");
            picks.Rows.Add("Sparky", "Aaron Baddeley");
            picks.Rows.Add("Sparky", "Anthony Kim");
            picks.Rows.Add("Sparky", "Brian Davis");
            picks.Rows.Add("Sparky", "Hunter Mahan");
            picks.Rows.Add("Sparky", "Jason Day");
            picks.Rows.Add("Sparky", "Jim Furyk");
            picks.Rows.Add("Sparky", "Rickie Fowler");
            picks.Rows.Add("Sparky", "Sean O'Hair");
            picks.Rows.Add("Sparky", "Tiger Woods");
            picks.Rows.Add("Sparky", "Trevor Immelman");
            picks.Rows.Add("Phil Lynch", "Cameron Tringale");
            picks.Rows.Add("Phil Lynch", "Camilo Villegas");
            picks.Rows.Add("Phil Lynch", "Fredrik Jacobson");
            picks.Rows.Add("Phil Lynch", "Jason Day");
            picks.Rows.Add("Phil Lynch", "Luke Donald");
            picks.Rows.Add("Phil Lynch", "Rickie Fowler");
            picks.Rows.Add("Phil Lynch", "Rory McIlroy");
            picks.Rows.Add("Phil Lynch", "Sang-Moon Bae");
            picks.Rows.Add("Phil Lynch", "Tiger Woods");
            picks.Rows.Add("Phil Lynch", "Tim Clark");
            picks.Rows.Add("Paul Howarth", "Anthony Kim");
            picks.Rows.Add("Paul Howarth", "Charl Schwartzel");
            picks.Rows.Add("Paul Howarth", "Dustin Johnson");
            picks.Rows.Add("Paul Howarth", "Geoff Ogilvy");
            picks.Rows.Add("Paul Howarth", "Jason Day");
            picks.Rows.Add("Paul Howarth", "Jim Furyk");
            picks.Rows.Add("Paul Howarth", "Rory McIlroy");
            picks.Rows.Add("Paul Howarth", "Sergio Garcia");
            picks.Rows.Add("Paul Howarth", "Tiger Woods");
            picks.Rows.Add("Paul Howarth", "Zach Johnson");
            picks.Rows.Add("Scott Taylor", "Bubba Watson");
            picks.Rows.Add("Scott Taylor", "Camilo Villegas");
            picks.Rows.Add("Scott Taylor", "Dustin Johnson");
            picks.Rows.Add("Scott Taylor", "Graeme McDowell");
            picks.Rows.Add("Scott Taylor", "Jim Furyk");
            picks.Rows.Add("Scott Taylor", "Justin Rose");
            picks.Rows.Add("Scott Taylor", "Louis Oosthuizen");
            picks.Rows.Add("Scott Taylor", "Rickie Fowler");
            picks.Rows.Add("Scott Taylor", "Sean O'Hair");
            picks.Rows.Add("Scott Taylor", "Tiger Woods");
            picks.Rows.Add("Simon Ball", "Adam Scott");
            picks.Rows.Add("Simon Ball", "Anthony Kim");
            picks.Rows.Add("Simon Ball", "Dustin Johnson");
            picks.Rows.Add("Simon Ball", "Jason Day");
            picks.Rows.Add("Simon Ball", "Jhonattan Vegas");
            picks.Rows.Add("Simon Ball", "Lee Westwood");
            picks.Rows.Add("Simon Ball", "Ricky Barnes");
            picks.Rows.Add("Simon Ball", "Rory McIlroy");
            picks.Rows.Add("Simon Ball", "Rory Sabbatini");
            picks.Rows.Add("Simon Ball", "Tiger Woods");
            picks.Rows.Add("Stephen Fontaine", "Aaron Baddeley");
            picks.Rows.Add("Stephen Fontaine", "Brandt Snedeker");
            picks.Rows.Add("Stephen Fontaine", "Bubba Watson");
            picks.Rows.Add("Stephen Fontaine", "John Senden");
            picks.Rows.Add("Stephen Fontaine", "Lee Westwood");
            picks.Rows.Add("Stephen Fontaine", "Lucas Glover");
            picks.Rows.Add("Stephen Fontaine", "Martin Laird");
            picks.Rows.Add("Stephen Fontaine", "Rory McIlroy");
            picks.Rows.Add("Stephen Fontaine", "Sean O'Hair");
            picks.Rows.Add("Stephen Fontaine", "Tiger Woods");
            picks.Rows.Add("Kevin Fontaine", "Brandt Snedeker");
            picks.Rows.Add("Kevin Fontaine", "Bubba Watson");
            picks.Rows.Add("Kevin Fontaine", "Chris Kirk");
            picks.Rows.Add("Kevin Fontaine", "Hunter Haas");
            picks.Rows.Add("Kevin Fontaine", "John Senden");
            picks.Rows.Add("Kevin Fontaine", "Lucas Glover");
            picks.Rows.Add("Kevin Fontaine", "Martin Laird");
            picks.Rows.Add("Kevin Fontaine", "Rickie Fowler");
            picks.Rows.Add("Kevin Fontaine", "Rory McIlroy");
            picks.Rows.Add("Kevin Fontaine", "Tiger Woods");
            picks.Rows.Add("Craig Arseneau", "Adam Scott");
            picks.Rows.Add("Craig Arseneau", "Bo Van Pelt");
            picks.Rows.Add("Craig Arseneau", "Jason Day");
            picks.Rows.Add("Craig Arseneau", "Martin Laird");
            picks.Rows.Add("Craig Arseneau", "Matt Bettencourt");
            picks.Rows.Add("Craig Arseneau", "Phil Mickelson");
            picks.Rows.Add("Craig Arseneau", "Rory McIlroy");
            picks.Rows.Add("Craig Arseneau", "Steve Flesch");
            picks.Rows.Add("Craig Arseneau", "Tiger Woods");
            picks.Rows.Add("Craig Arseneau", "Trevor Immelman");
            picks.Rows.Add("Yvonne Mootoo", "Bubba Watson");
            picks.Rows.Add("Yvonne Mootoo", "Jim Furyk");
            picks.Rows.Add("Yvonne Mootoo", "Kyle Stanley");
            picks.Rows.Add("Yvonne Mootoo", "Michael Bradley");
            picks.Rows.Add("Yvonne Mootoo", "Rickie Fowler");
            picks.Rows.Add("Yvonne Mootoo", "Rory McIlroy");
            picks.Rows.Add("Yvonne Mootoo", "Tiger Woods");
            picks.Rows.Add("Yvonne Mootoo", "Trevor Immelman");
            picks.Rows.Add("Yvonne Mootoo", "Webb Simpson");
            picks.Rows.Add("Yvonne Mootoo", "Zach Johnson");
            picks.Rows.Add("J. McCullough", "Adam Scott");
            picks.Rows.Add("J. McCullough", "Anthony Kim");
            picks.Rows.Add("J. McCullough", "Bubba Watson");
            picks.Rows.Add("J. McCullough", "Camilo Villegas");
            picks.Rows.Add("J. McCullough", "Gary Woodland");
            picks.Rows.Add("J. McCullough", "J.J. Killeen");
            picks.Rows.Add("J. McCullough", "Jason Day");
            picks.Rows.Add("J. McCullough", "Rory McIlroy");
            picks.Rows.Add("J. McCullough", "Sean O'Hair");
            picks.Rows.Add("J. McCullough", "Tiger Woods");
            picks.Rows.Add("Doug Young", "Aaron Baddeley");
            picks.Rows.Add("Doug Young", "Adam Scott");
            picks.Rows.Add("Doug Young", "Bo Van Pelt");
            picks.Rows.Add("Doug Young", "Charles Howell III");
            picks.Rows.Add("Doug Young", "Hunter Mahan");
            picks.Rows.Add("Doug Young", "Lee Westwood");
            picks.Rows.Add("Doug Young", "Rickie Fowler");
            picks.Rows.Add("Doug Young", "Rory McIlroy");
            picks.Rows.Add("Doug Young", "Tiger Woods");
            picks.Rows.Add("Doug Young", "Trevor Immelman");
            picks.Rows.Add("Peter Tyson", "Geoff Ogilvy");
            picks.Rows.Add("Peter Tyson", "Jason Day");
            picks.Rows.Add("Peter Tyson", "Jhonattan Vegas");
            picks.Rows.Add("Peter Tyson", "Jim Furyk");
            picks.Rows.Add("Peter Tyson", "Lucas Glover");
            picks.Rows.Add("Peter Tyson", "Ryuji Imada");
            picks.Rows.Add("Peter Tyson", "Sergio Garcia");
            picks.Rows.Add("Peter Tyson", "Steve Stricker");
            picks.Rows.Add("Peter Tyson", "Tiger Woods");
            picks.Rows.Add("Peter Tyson", "Zach Johnson");
            picks.Rows.Add("Glenn Kenn", "Anthony Kim");
            picks.Rows.Add("Glenn Kenn", "Charles Howell III");
            picks.Rows.Add("Glenn Kenn", "Ernie Els");
            picks.Rows.Add("Glenn Kenn", "Jim Furyk");
            picks.Rows.Add("Glenn Kenn", "K.J. Choi");
            picks.Rows.Add("Glenn Kenn", "Padraig Harrington");
            picks.Rows.Add("Glenn Kenn", "Phil Mickelson");
            picks.Rows.Add("Glenn Kenn", "Rickie Fowler");
            picks.Rows.Add("Glenn Kenn", "Tiger Woods");
            picks.Rows.Add("Glenn Kenn", "Y.E. Yang");
            picks.Rows.Add("Golfnfool", "Bo Van Pelt");
            picks.Rows.Add("Golfnfool", "Charles Howell III");
            picks.Rows.Add("Golfnfool", "Hunter Mahan");
            picks.Rows.Add("Golfnfool", "Lee Westwood");
            picks.Rows.Add("Golfnfool", "Matt Kuchar");
            picks.Rows.Add("Golfnfool", "Rickie Fowler");
            picks.Rows.Add("Golfnfool", "Rory McIlroy");
            picks.Rows.Add("Golfnfool", "Ryan Moore");
            picks.Rows.Add("Golfnfool", "Tiger Woods");
            picks.Rows.Add("Golfnfool", "Zach Johnson");
            picks.Rows.Add("Simon Brown", "Adam Scott");
            picks.Rows.Add("Simon Brown", "Anthony Kim");
            picks.Rows.Add("Simon Brown", "Ben Crane");
            picks.Rows.Add("Simon Brown", "Dustin Johnson");
            picks.Rows.Add("Simon Brown", "Geoff Ogilvy");
            picks.Rows.Add("Simon Brown", "Ian Poulter");
            picks.Rows.Add("Simon Brown", "Rickie Fowler");
            picks.Rows.Add("Simon Brown", "Ryan Moore");
            picks.Rows.Add("Simon Brown", "Steve Marino");
            picks.Rows.Add("Simon Brown", "Tiger Woods");
            picks.Rows.Add("Marian Brown", "Adam Scott");
            picks.Rows.Add("Marian Brown", "Camilo Villegas");
            picks.Rows.Add("Marian Brown", "Ian Poulter");
            picks.Rows.Add("Marian Brown", "Jason Day");
            picks.Rows.Add("Marian Brown", "Justin Rose");
            picks.Rows.Add("Marian Brown", "Padraig Harrington");
            picks.Rows.Add("Marian Brown", "Rickie Fowler");
            picks.Rows.Add("Marian Brown", "Sergio Garcia");
            picks.Rows.Add("Marian Brown", "Tiger Woods");
            picks.Rows.Add("Marian Brown", "Zach Johnson");
            picks.Rows.Add("Robert Brown", "Adam Scott");
            picks.Rows.Add("Robert Brown", "Ian Poulter");
            picks.Rows.Add("Robert Brown", "Lee Westwood");
            picks.Rows.Add("Robert Brown", "Luke Donald");
            picks.Rows.Add("Robert Brown", "Rickie Fowler");
            picks.Rows.Add("Robert Brown", "Robert Karlsson");
            picks.Rows.Add("Robert Brown", "Rory McIlroy");
            picks.Rows.Add("Robert Brown", "Sergio Garcia");
            picks.Rows.Add("Robert Brown", "Tiger Woods");
            picks.Rows.Add("Robert Brown", "Zach Johnson");
            picks.Rows.Add("Matthew Gordon", "Anthony Kim");
            picks.Rows.Add("Matthew Gordon", "Graeme McDowell");
            picks.Rows.Add("Matthew Gordon", "Jim Furyk");
            picks.Rows.Add("Matthew Gordon", "K.J. Choi");
            picks.Rows.Add("Matthew Gordon", "Lee Westwood");
            picks.Rows.Add("Matthew Gordon", "Matt Kuchar");
            picks.Rows.Add("Matthew Gordon", "Phil Mickelson");
            picks.Rows.Add("Matthew Gordon", "Rickie Fowler");
            picks.Rows.Add("Matthew Gordon", "Rory McIlroy");
            picks.Rows.Add("Matthew Gordon", "Tiger Woods");
            picks.Rows.Add("Ron Mark", "Aaron Baddeley");
            picks.Rows.Add("Ron Mark", "Adam Scott");
            picks.Rows.Add("Ron Mark", "Jason Day");
            picks.Rows.Add("Ron Mark", "Pat Perez");
            picks.Rows.Add("Ron Mark", "Ryan Palmer");
            picks.Rows.Add("Ron Mark", "Ryo Ishikawa");
            picks.Rows.Add("Ron Mark", "Sunghoon Kang");
            picks.Rows.Add("Ron Mark", "Tiger Woods");
            picks.Rows.Add("Ron Mark", "Trevor Immelman");
            picks.Rows.Add("Ron Mark", "Y.E. Yang");
            picks.Rows.Add("UK Rules Golf", "Brian Davis");
            picks.Rows.Add("UK Rules Golf", "Darren Clarke");
            picks.Rows.Add("UK Rules Golf", "Graeme McDowell");
            picks.Rows.Add("UK Rules Golf", "Ian Poulter");
            picks.Rows.Add("UK Rules Golf", "Justin Rose");
            picks.Rows.Add("UK Rules Golf", "Lee Westwood");
            picks.Rows.Add("UK Rules Golf", "Luke Donald");
            picks.Rows.Add("UK Rules Golf", "Martin Laird");
            picks.Rows.Add("UK Rules Golf", "Paul Casey");
            picks.Rows.Add("UK Rules Golf", "Rory McIlroy");
            picks.Rows.Add("Shaun McBride", "Anthony Kim");
            picks.Rows.Add("Shaun McBride", "Bill Haas");
            picks.Rows.Add("Shaun McBride", "Dustin Johnson");
            picks.Rows.Add("Shaun McBride", "Ian Poulter");
            picks.Rows.Add("Shaun McBride", "Jason Day");
            picks.Rows.Add("Shaun McBride", "Lee Westwood");
            picks.Rows.Add("Shaun McBride", "Padraig Harrington");
            picks.Rows.Add("Shaun McBride", "Rickie Fowler");
            picks.Rows.Add("Shaun McBride", "Rory McIlroy");
            picks.Rows.Add("Shaun McBride", "Tiger Woods");
            picks.Rows.Add("Ron Mark", "Aaron Baddeley");
            picks.Rows.Add("Ron Mark", "Adam Scott");
            picks.Rows.Add("Ron Mark", "Jason Day");
            picks.Rows.Add("Ron Mark", "Pat Perez");
            picks.Rows.Add("Ron Mark", "Ryan Palmer");
            picks.Rows.Add("Ron Mark", "Ryo Ishikawa");
            picks.Rows.Add("Ron Mark", "Sunghoon Kang");
            picks.Rows.Add("Ron Mark", "Tiger Woods");
            picks.Rows.Add("Ron Mark", "Trevor Immelman");
            picks.Rows.Add("Ron Mark", "Y.E. Yang");
            picks.Rows.Add("Actor 2", "Brendan Steele");
            picks.Rows.Add("Actor 2", "Bubba Watson");
            picks.Rows.Add("Actor 2", "Camilo Villegas");
            picks.Rows.Add("Actor 2", "Gary Woodland");
            picks.Rows.Add("Actor 2", "Jhonattan Vegas");
            picks.Rows.Add("Actor 2", "Lee Westwood");
            picks.Rows.Add("Actor 2", "Phil Mickelson");
            picks.Rows.Add("Actor 2", "Rickie Fowler");
            picks.Rows.Add("Actor 2", "Rory McIlroy");
            picks.Rows.Add("Actor 2", "Tiger Woods");
            picks.Rows.Add("David Service 2", "Adam Scott");
            picks.Rows.Add("David Service 2", "Graeme McDowell");
            picks.Rows.Add("David Service 2", "J.B. Holmes");
            picks.Rows.Add("David Service 2", "Jason Day");
            picks.Rows.Add("David Service 2", "Keegan Bradley");
            picks.Rows.Add("David Service 2", "Lee Westwood");
            picks.Rows.Add("David Service 2", "Retief Goosen");
            picks.Rows.Add("David Service 2", "Rickie Fowler");
            picks.Rows.Add("David Service 2", "Sergio Garcia");
            picks.Rows.Add("David Service 2", "Tiger Woods");
            picks.Rows.Add("Ed Williston", "Bubba Watson");
            picks.Rows.Add("Ed Williston", "Camilo Villegas");
            picks.Rows.Add("Ed Williston", "Charl Schwartzel");
            picks.Rows.Add("Ed Williston", "Hunter Mahan");
            picks.Rows.Add("Ed Williston", "Jhonattan Vegas");
            picks.Rows.Add("Ed Williston", "Keegan Bradley");
            picks.Rows.Add("Ed Williston", "Lee Westwood");
            picks.Rows.Add("Ed Williston", "Rory McIlroy");
            picks.Rows.Add("Ed Williston", "Sergio Garcia");
            picks.Rows.Add("Ed Williston", "Tiger Woods");
            picks.Rows.Add("Rob Bacon", "Anthony Kim");
            picks.Rows.Add("Rob Bacon", "Ben Curtis");
            picks.Rows.Add("Rob Bacon", "Hunter Mahan");
            picks.Rows.Add("Rob Bacon", "Justin Rose");
            picks.Rows.Add("Rob Bacon", "Lucas Glover");
            picks.Rows.Add("Rob Bacon", "Phil Mickelson");
            picks.Rows.Add("Rob Bacon", "Steve Flesch");
            picks.Rows.Add("Rob Bacon", "Steve Stricker");
            picks.Rows.Add("Rob Bacon", "Stuart Appleby");
            picks.Rows.Add("Rob Bacon", "Tiger Woods");
            picks.Rows.Add("Brendan McBride", "Adam Scott");
            picks.Rows.Add("Brendan McBride", "Charl Schwartzel");
            picks.Rows.Add("Brendan McBride", "Dustin Johnson");
            picks.Rows.Add("Brendan McBride", "Jim Furyk");
            picks.Rows.Add("Brendan McBride", "Padraig Harrington");
            picks.Rows.Add("Brendan McBride", "Paul Casey");
            picks.Rows.Add("Brendan McBride", "Phil Mickelson");
            picks.Rows.Add("Brendan McBride", "Rory McIlroy");
            picks.Rows.Add("Brendan McBride", "Sergio Garcia");
            picks.Rows.Add("Brendan McBride", "Tiger Woods");
            picks.Rows.Add("Karlene 2", "Adam Scott");
            picks.Rows.Add("Karlene 2", "Anthony Kim");
            picks.Rows.Add("Karlene 2", "Brian Davis");
            picks.Rows.Add("Karlene 2", "Bryce Molder");
            picks.Rows.Add("Karlene 2", "Charles Howell III");
            picks.Rows.Add("Karlene 2", "Justin Leonard");
            picks.Rows.Add("Karlene 2", "Justin Rose");
            picks.Rows.Add("Karlene 2", "Kevan Na");
            picks.Rows.Add("Karlene 2", "Robert Karlsson");
            picks.Rows.Add("Karlene 2", "Tiger Woods");
            picks.Rows.Add("Phil Curtis", "Anthony Kim");
            picks.Rows.Add("Phil Curtis", "Bubba Watson");
            picks.Rows.Add("Phil Curtis", "Jason Day");
            picks.Rows.Add("Phil Curtis", "Justin Rose");
            picks.Rows.Add("Phil Curtis", "Keegan Bradley");
            picks.Rows.Add("Phil Curtis", "Martin Kaymer");
            picks.Rows.Add("Phil Curtis", "Paul Casey");
            picks.Rows.Add("Phil Curtis", "Rory McIlroy");
            picks.Rows.Add("Phil Curtis", "Steve Marino");
            picks.Rows.Add("Phil Curtis", "Tiger Woods");
            picks.Rows.Add("David Service 1", "Anthony Kim");
            picks.Rows.Add("David Service 1", "Dustin Johnson");
            picks.Rows.Add("David Service 1", "Ernie Els");
            picks.Rows.Add("David Service 1", "Gary Woodland");
            picks.Rows.Add("David Service 1", "Geoff Ogilvy");
            picks.Rows.Add("David Service 1", "Keegan Bradley");
            picks.Rows.Add("David Service 1", "Paul Casey");
            picks.Rows.Add("David Service 1", "Rickie Fowler");
            picks.Rows.Add("David Service 1", "Tiger Woods");
            picks.Rows.Add("David Service 1", "Trevor Immelman");
            picks.Rows.Add("Kate", "Anthony Kim");
            picks.Rows.Add("Kate", "Chez Reavie");
            picks.Rows.Add("Kate", "Ernie Els");
            picks.Rows.Add("Kate", "Gary Woodland");
            picks.Rows.Add("Kate", "Geoff Ogilvy");
            picks.Rows.Add("Kate", "Keegan Bradley");
            picks.Rows.Add("Kate", "Rickie Fowler");
            picks.Rows.Add("Kate", "Sergio Garcia");
            picks.Rows.Add("Kate", "Tiger Woods");
            picks.Rows.Add("Kate", "Tommy Gainey");
            picks.Rows.Add("Maddie", "Aaron Baddeley");
            picks.Rows.Add("Maddie", "Camilo Villegas");
            picks.Rows.Add("Maddie", "Geoff Ogilvy");
            picks.Rows.Add("Maddie", "Jhonattan Vegas");
            picks.Rows.Add("Maddie", "Luke Donald");
            picks.Rows.Add("Maddie", "Marc Leishman");
            picks.Rows.Add("Maddie", "Padraig Harrington");
            picks.Rows.Add("Maddie", "Retief Goosen");
            picks.Rows.Add("Maddie", "Ryan Moore");
            picks.Rows.Add("Maddie", "Tiger Woods");
            picks.Rows.Add("Adam Carpenter", "Adam Scott");
            picks.Rows.Add("Adam Carpenter", "Bubba Watson");
            picks.Rows.Add("Adam Carpenter", "Camilo Villegas");
            picks.Rows.Add("Adam Carpenter", "Dustin Johnson");
            picks.Rows.Add("Adam Carpenter", "Graeme McDowell");
            picks.Rows.Add("Adam Carpenter", "Jhonattan Vegas");
            picks.Rows.Add("Adam Carpenter", "Paul Casey");
            picks.Rows.Add("Adam Carpenter", "Rickie Fowler");
            picks.Rows.Add("Adam Carpenter", "Ricky Barnes");
            picks.Rows.Add("Adam Carpenter", "Tiger Woods");
            picks.Rows.Add("Legend 1", "Bubba Watson");
            picks.Rows.Add("Legend 1", "Charl Schwartzel");
            picks.Rows.Add("Legend 1", "Dustin Johnson");
            picks.Rows.Add("Legend 1", "Jim Furyk");
            picks.Rows.Add("Legend 1", "Keegan Bradley");
            picks.Rows.Add("Legend 1", "Lee Westwood");
            picks.Rows.Add("Legend 1", "Paul Casey");
            picks.Rows.Add("Legend 1", "Rickie Fowler");
            picks.Rows.Add("Legend 1", "Rory McIlroy");
            picks.Rows.Add("Legend 1", "Tiger Woods");
            picks.Rows.Add("David Lewis", "Adam Scott");
            picks.Rows.Add("David Lewis", "Camilo Villegas");
            picks.Rows.Add("David Lewis", "Charl Schwartzel");
            picks.Rows.Add("David Lewis", "Charles Howell III");
            picks.Rows.Add("David Lewis", "Graeme McDowell");
            picks.Rows.Add("David Lewis", "Jim Furyk");
            picks.Rows.Add("David Lewis", "Lucas Glover");
            picks.Rows.Add("David Lewis", "Matt Kuchar");
            picks.Rows.Add("David Lewis", "Rory McIlroy");
            picks.Rows.Add("David Lewis", "Tiger Woods");
            picks.Rows.Add("Karlene 1", "Andres Romero");
            picks.Rows.Add("Karlene 1", "Blake Adams");
            picks.Rows.Add("Karlene 1", "Bryce Molder");
            picks.Rows.Add("Karlene 1", "Camilo Villegas");
            picks.Rows.Add("Karlene 1", "Hunter Haas");
            picks.Rows.Add("Karlene 1", "Hunter Mahan");
            picks.Rows.Add("Karlene 1", "K.J. Choi");
            picks.Rows.Add("Karlene 1", "Rory Sabbatini");
            picks.Rows.Add("Karlene 1", "Vaughn Taylor");
            picks.Rows.Add("Karlene 1", "Y.E. Yang");
            picks.Rows.Add("David Luke", "Angel Cabrera");
            picks.Rows.Add("David Luke", "Ben Curtis");
            picks.Rows.Add("David Luke", "Bubba Watson");
            picks.Rows.Add("David Luke", "Keegan Bradley");
            picks.Rows.Add("David Luke", "Matt Kuchar");
            picks.Rows.Add("David Luke", "Phil Mickelson");
            picks.Rows.Add("David Luke", "Rickie Fowler");
            picks.Rows.Add("David Luke", "Steve Flesch");
            picks.Rows.Add("David Luke", "Stuart Appleby");
            picks.Rows.Add("David Luke", "Tiger Woods");
            picks.Rows.Add("Actor 1", "Adam Scott");
            picks.Rows.Add("Actor 1", "Anthony Kim");
            picks.Rows.Add("Actor 1", "Jonathan Byrd");
            picks.Rows.Add("Actor 1", "Keegan Bradley");
            picks.Rows.Add("Actor 1", "Lee Westwood");
            picks.Rows.Add("Actor 1", "Mark Wilson");
            picks.Rows.Add("Actor 1", "Martin Laird");
            picks.Rows.Add("Actor 1", "Michael Bradley");
            picks.Rows.Add("Actor 1", "Rory McIlroy");
            picks.Rows.Add("Actor 1", "Tiger Woods");
            picks.Rows.Add("Jason Connors", "Aaron Baddeley");
            picks.Rows.Add("Jason Connors", "Adam Scott");
            picks.Rows.Add("Jason Connors", "Bubba Watson");
            picks.Rows.Add("Jason Connors", "Dustin Johnson");
            picks.Rows.Add("Jason Connors", "Graeme McDowell");
            picks.Rows.Add("Jason Connors", "Lee Westwood");
            picks.Rows.Add("Jason Connors", "Louis Oosthuizen");
            picks.Rows.Add("Jason Connors", "Rory McIlroy");
            picks.Rows.Add("Jason Connors", "Tiger Woods");
            picks.Rows.Add("Jason Connors", "Zach Johnson");
            picks.Rows.Add("Linda Lewis", "Bill Haas");
            picks.Rows.Add("Linda Lewis", "Dustin Johnson");
            picks.Rows.Add("Linda Lewis", "Jhonattan Vegas");
            picks.Rows.Add("Linda Lewis", "Lee Westwood");
            picks.Rows.Add("Linda Lewis", "Paul Casey");
            picks.Rows.Add("Linda Lewis", "Rickie Fowler");
            picks.Rows.Add("Linda Lewis", "Rory McIlroy");
            picks.Rows.Add("Linda Lewis", "Sergio Garcia");
            picks.Rows.Add("Linda Lewis", "Steve Stricker");
            picks.Rows.Add("Linda Lewis", "Tiger Woods");
            picks.Rows.Add("Saverio Bruno", "Brendon Todd");
            picks.Rows.Add("Saverio Bruno", "Chad Campbell");
            picks.Rows.Add("Saverio Bruno", "Luke Donald");
            picks.Rows.Add("Saverio Bruno", "Phil Mickelson");
            picks.Rows.Add("Saverio Bruno", "Rickie Fowler");
            picks.Rows.Add("Saverio Bruno", "Roberto Castro");
            picks.Rows.Add("Saverio Bruno", "Rory McIlroy");
            picks.Rows.Add("Saverio Bruno", "Tiger Woods");
            picks.Rows.Add("Saverio Bruno", "Vijay Singh");
            picks.Rows.Add("Saverio Bruno", "Zach Johnson");
            picks.Rows.Add("Spall 1", "Brendan Steele");
            picks.Rows.Add("Spall 1", "Bryce Molder");
            picks.Rows.Add("Spall 1", "D.A. Points");
            picks.Rows.Add("Spall 1", "Geoff Ogilvy");
            picks.Rows.Add("Spall 1", "Rickie Fowler");
            picks.Rows.Add("Spall 1", "Ryan Moore");
            picks.Rows.Add("Spall 1", "Scott Stallings");
            picks.Rows.Add("Spall 1", "Steve Marino");
            picks.Rows.Add("Spall 1", "Tommy Gainey");
            picks.Rows.Add("Spall 1", "Zach Johnson");
            picks.Rows.Add("Legend 2", "Anthony Kim");
            picks.Rows.Add("Legend 2", "Bill Haas");
            picks.Rows.Add("Legend 2", "Hunter Mahan");
            picks.Rows.Add("Legend 2", "Jason Day");
            picks.Rows.Add("Legend 2", "Jhonattan Vegas");
            picks.Rows.Add("Legend 2", "Lee Westwood");
            picks.Rows.Add("Legend 2", "Lucas Glover");
            picks.Rows.Add("Legend 2", "Rickie Fowler");
            picks.Rows.Add("Legend 2", "Rory McIlroy");
            picks.Rows.Add("Legend 2", "Tiger Woods");
            picks.Rows.Add("Michael Liberty", "Adam Scott");
            picks.Rows.Add("Michael Liberty", "Anthony Kim");
            picks.Rows.Add("Michael Liberty", "Charl Schwartzel");
            picks.Rows.Add("Michael Liberty", "Davis Love III");
            picks.Rows.Add("Michael Liberty", "Dustin Johnson");
            picks.Rows.Add("Michael Liberty", "Ernie Els");
            picks.Rows.Add("Michael Liberty", "Graeme McDowell");
            picks.Rows.Add("Michael Liberty", "Padraig Harrington");
            picks.Rows.Add("Michael Liberty", "Phil Mickelson");
            picks.Rows.Add("Michael Liberty", "Tiger Woods");
            picks.Rows.Add("Patrick  Barbieri", "Aaron Baddeley");
            picks.Rows.Add("Patrick  Barbieri", "Anthony Kim");
            picks.Rows.Add("Patrick  Barbieri", "Bubba Watson");
            picks.Rows.Add("Patrick  Barbieri", "Camilo Villegas");
            picks.Rows.Add("Patrick  Barbieri", "Graeme McDowell");
            picks.Rows.Add("Patrick  Barbieri", "Lucas Glover");
            picks.Rows.Add("Patrick  Barbieri", "Phil Mickelson");
            picks.Rows.Add("Patrick  Barbieri", "Rickie Fowler");
            picks.Rows.Add("Patrick  Barbieri", "Robert Karlsson");
            picks.Rows.Add("Patrick  Barbieri", "Tiger Woods");
            picks.Rows.Add("Lynda Vysoki", "Adam Scott");
            picks.Rows.Add("Lynda Vysoki", "Chris DiMarco");
            picks.Rows.Add("Lynda Vysoki", "D.J. Trahan");
            picks.Rows.Add("Lynda Vysoki", "Ernie Els");
            picks.Rows.Add("Lynda Vysoki", "Jim Furyk");
            picks.Rows.Add("Lynda Vysoki", "K.J. Choi");
            picks.Rows.Add("Lynda Vysoki", "Phil Mickelson");
            picks.Rows.Add("Lynda Vysoki", "Scott Verplank");
            picks.Rows.Add("Lynda Vysoki", "Tiger Woods");
            picks.Rows.Add("Lynda Vysoki", "Vijay Singh");
            picks.Rows.Add("David Gale", "Dustin Johnson");
            picks.Rows.Add("David Gale", "Gary Woodland");
            picks.Rows.Add("David Gale", "Jason Day");
            picks.Rows.Add("David Gale", "Keegan Bradley");
            picks.Rows.Add("David Gale", "Lee Westwood");
            picks.Rows.Add("David Gale", "Ricky Barnes");
            picks.Rows.Add("David Gale", "Rory McIlroy");
            picks.Rows.Add("David Gale", "Sergio Garcia");
            picks.Rows.Add("David Gale", "Tiger Woods");
            picks.Rows.Add("David Gale", "Tim Clark");
            picks.Rows.Add("Ryan Sadler", "Adam Scott");
            picks.Rows.Add("Ryan Sadler", "Anthony Kim");
            picks.Rows.Add("Ryan Sadler", "Bubba Watson");
            picks.Rows.Add("Ryan Sadler", "Keegan Bradley");
            picks.Rows.Add("Ryan Sadler", "Lee Westwood");
            picks.Rows.Add("Ryan Sadler", "Martin Kaymer");
            picks.Rows.Add("Ryan Sadler", "Rory McIlroy");
            picks.Rows.Add("Ryan Sadler", "Steve Stricker");
            picks.Rows.Add("Ryan Sadler", "Tiger Woods");
            picks.Rows.Add("Ryan Sadler", "Zach Johnson");
            picks.Rows.Add("Rick Kozlowski", "Angel Cabrera");
            picks.Rows.Add("Rick Kozlowski", "Anthony Kim");
            picks.Rows.Add("Rick Kozlowski", "Bill Haas");
            picks.Rows.Add("Rick Kozlowski", "Brian Gay");
            picks.Rows.Add("Rick Kozlowski", "Camilo Villegas");
            picks.Rows.Add("Rick Kozlowski", "Keegan Bradley");
            picks.Rows.Add("Rick Kozlowski", "Nick Watney");
            picks.Rows.Add("Rick Kozlowski", "Paul Casey");
            picks.Rows.Add("Rick Kozlowski", "Ryan Palmer");
            picks.Rows.Add("Rick Kozlowski", "Tiger Woods");
            picks.Rows.Add("Mark Graham", "Ben Crane");
            picks.Rows.Add("Mark Graham", "Brendan Steele");
            picks.Rows.Add("Mark Graham", "Dustin Johnson");
            picks.Rows.Add("Mark Graham", "Hunter Mahan");
            picks.Rows.Add("Mark Graham", "Jim Furyk");
            picks.Rows.Add("Mark Graham", "Lee Westwood");
            picks.Rows.Add("Mark Graham", "Rory McIlroy");
            picks.Rows.Add("Mark Graham", "Sean O'Hair");
            picks.Rows.Add("Mark Graham", "Steve Stricker");
            picks.Rows.Add("Mark Graham", "Tim Clark");
            picks.Rows.Add("Rick Thorpe", "Adam Scott");
            picks.Rows.Add("Rick Thorpe", "Graeme McDowell");
            picks.Rows.Add("Rick Thorpe", "Greg Chalmers");
            picks.Rows.Add("Rick Thorpe", "Ian Poulter");
            picks.Rows.Add("Rick Thorpe", "Jason Day");
            picks.Rows.Add("Rick Thorpe", "Jerry Kelly");
            picks.Rows.Add("Rick Thorpe", "Matt Kuchar");
            picks.Rows.Add("Rick Thorpe", "Sergio Garcia");
            picks.Rows.Add("Rick Thorpe", "Tiger Woods");
            picks.Rows.Add("Rick Thorpe", "Zach Johnson");
            picks.Rows.Add("Judi Mooney", "Brandt Jobe");
            picks.Rows.Add("Judi Mooney", "Jim Furyk");
            picks.Rows.Add("Judi Mooney", "Kyle Stanley");
            picks.Rows.Add("Judi Mooney", "Lucas Glover");
            picks.Rows.Add("Judi Mooney", "Luke Donald");
            picks.Rows.Add("Judi Mooney", "Robert Garrigus");
            picks.Rows.Add("Judi Mooney", "Robert Karlsson");
            picks.Rows.Add("Judi Mooney", "Sean O'Hair");
            picks.Rows.Add("Judi Mooney", "Sergio Garcia");
            picks.Rows.Add("Judi Mooney", "Tiger Woods");
            picks.Rows.Add("Myahmoo", "Adam Scott");
            picks.Rows.Add("Myahmoo", "Bubba Watson");
            picks.Rows.Add("Myahmoo", "Graeme McDowell");
            picks.Rows.Add("Myahmoo", "Jason Day");
            picks.Rows.Add("Myahmoo", "Jonathan Byrd");
            picks.Rows.Add("Myahmoo", "Martin Kaymer");
            picks.Rows.Add("Myahmoo", "Rickie Fowler");
            picks.Rows.Add("Myahmoo", "Rory McIlroy");
            picks.Rows.Add("Myahmoo", "Tiger Woods");
            picks.Rows.Add("Myahmoo", "Trevor Immelman");
            picks.Rows.Add("John McBride", "Bubba Watson");
            picks.Rows.Add("John McBride", "Jason Day");
            picks.Rows.Add("John McBride", "Jason Dufner");
            picks.Rows.Add("John McBride", "Jim Furyk");
            picks.Rows.Add("John McBride", "K.J. Choi");
            picks.Rows.Add("John McBride", "Lee Westwood");
            picks.Rows.Add("John McBride", "Paul Casey");
            picks.Rows.Add("John McBride", "Rory McIlroy");
            picks.Rows.Add("John McBride", "Sergio Garcia");
            picks.Rows.Add("John McBride", "Tiger Woods");
            picks.Rows.Add("Minesh Patel", "Bubba Watson");
            picks.Rows.Add("Minesh Patel", "Cameron Tringale");
            picks.Rows.Add("Minesh Patel", "D.A. Points");
            picks.Rows.Add("Minesh Patel", "Keegan Bradley");
            picks.Rows.Add("Minesh Patel", "Lee Westwood");
            picks.Rows.Add("Minesh Patel", "Mark Wilson");
            picks.Rows.Add("Minesh Patel", "Martin Kaymer");
            picks.Rows.Add("Minesh Patel", "Matt Kuchar");
            picks.Rows.Add("Minesh Patel", "Rory McIlroy");
            picks.Rows.Add("Minesh Patel", "Tiger Woods");
            picks.Rows.Add("Luzia Jean Pedro", "Adam Scott");
            picks.Rows.Add("Luzia Jean Pedro", "Bill Lunde");
            picks.Rows.Add("Luzia Jean Pedro", "Bobby Gates");
            picks.Rows.Add("Luzia Jean Pedro", "Bryce Molder");
            picks.Rows.Add("Luzia Jean Pedro", "Bubba Watson");
            picks.Rows.Add("Luzia Jean Pedro", "David Toms");
            picks.Rows.Add("Luzia Jean Pedro", "Jim Furyk");
            picks.Rows.Add("Luzia Jean Pedro", "Rory Sabbatini");
            picks.Rows.Add("Luzia Jean Pedro", "Sean O'Hair");
            picks.Rows.Add("Luzia Jean Pedro", "Tiger Woods");
            picks.Rows.Add("Don Mooney", "Adam Scott");
            picks.Rows.Add("Don Mooney", "Ian Poulter");
            picks.Rows.Add("Don Mooney", "J.B. Holmes");
            picks.Rows.Add("Don Mooney", "John Merrick");
            picks.Rows.Add("Don Mooney", "Louis Oosthuizen");
            picks.Rows.Add("Don Mooney", "Retief Goosen");
            picks.Rows.Add("Don Mooney", "Steve Stricker");
            picks.Rows.Add("Don Mooney", "Tiger Woods");
            picks.Rows.Add("Don Mooney", "Tom Pernice Jr.");
            picks.Rows.Add("Don Mooney", "Luke Donald");
            picks.Rows.Add("Ejaz Asgarali", "Adam Scott");
            picks.Rows.Add("Ejaz Asgarali", "Anthony Kim");
            picks.Rows.Add("Ejaz Asgarali", "Camilo Villegas");
            picks.Rows.Add("Ejaz Asgarali", "Charles Howell III");
            picks.Rows.Add("Ejaz Asgarali", "David Toms");
            picks.Rows.Add("Ejaz Asgarali", "Jhonattan Vegas");
            picks.Rows.Add("Ejaz Asgarali", "Keegan Bradley");
            picks.Rows.Add("Ejaz Asgarali", "Michael Thompson");
            picks.Rows.Add("Ejaz Asgarali", "Paul Casey");
            picks.Rows.Add("Ejaz Asgarali", "Tiger Woods");
            picks.Rows.Add("Chris Luck", "Anthony Kim");
            picks.Rows.Add("Chris Luck", "Bubba Watson");
            picks.Rows.Add("Chris Luck", "Dustin Johnson");
            picks.Rows.Add("Chris Luck", "Jason Day");
            picks.Rows.Add("Chris Luck", "Paul Casey");
            picks.Rows.Add("Chris Luck", "Phil Mickelson");
            picks.Rows.Add("Chris Luck", "Ryuji Imada");
            picks.Rows.Add("Chris Luck", "Stewart Cink");
            picks.Rows.Add("Chris Luck", "Tiger Woods");
            picks.Rows.Add("Chris Luck", "Tim Clark");
            picks.Rows.Add("Spall 2", "Adam Scott");
            picks.Rows.Add("Spall 2", "Bobby Gates");
            picks.Rows.Add("Spall 2", "Brendan Steele");
            picks.Rows.Add("Spall 2", "Bubba Watson");
            picks.Rows.Add("Spall 2", "Charley Hoffman");
            picks.Rows.Add("Spall 2", "Keegan Bradley");
            picks.Rows.Add("Spall 2", "Rickie Fowler");
            picks.Rows.Add("Spall 2", "Steve Marino");
            picks.Rows.Add("Spall 2", "Stuart Appleby");
            picks.Rows.Add("Spall 2", "Tiger Woods");
            picks.Rows.Add("John Brown 1", "Hunter Mahan");
            picks.Rows.Add("John Brown 1", "Jason Day");
            picks.Rows.Add("John Brown 1", "Jim Furyk");
            picks.Rows.Add("John Brown 1", "Lee Westwood");
            picks.Rows.Add("John Brown 1", "Matt Kuchar");
            picks.Rows.Add("John Brown 1", "Paul Casey");
            picks.Rows.Add("John Brown 1", "Phil Mickelson");
            picks.Rows.Add("John Brown 1", "Rory McIlroy");
            picks.Rows.Add("John Brown 1", "Tiger Woods");
            picks.Rows.Add("John Brown 1", "Tim Clark");
            picks.Rows.Add("John Brown 2", "Camilo Villegas");
            picks.Rows.Add("John Brown 2", "Dustin Johnson");
            picks.Rows.Add("John Brown 2", "Hunter Mahan");
            picks.Rows.Add("John Brown 2", "Jim Furyk");
            picks.Rows.Add("John Brown 2", "Lee Westwood");
            picks.Rows.Add("John Brown 2", "Phil Mickelson");
            picks.Rows.Add("John Brown 2", "Rickie Fowler");
            picks.Rows.Add("John Brown 2", "Rory McIlroy");
            picks.Rows.Add("John Brown 2", "Tiger Woods");
            picks.Rows.Add("John Brown 2", "Zach Johnson");
            picks.Rows.Add("Grant Allman", "Anthony Kim");
            picks.Rows.Add("Grant Allman", "Charl Schwartzel");
            picks.Rows.Add("Grant Allman", "Dustin Johnson");
            picks.Rows.Add("Grant Allman", "Geoff Ogilvy");
            picks.Rows.Add("Grant Allman", "Graeme McDowell");
            picks.Rows.Add("Grant Allman", "Jason Day");
            picks.Rows.Add("Grant Allman", "Rickie Fowler");
            picks.Rows.Add("Grant Allman", "Rory McIlroy");
            picks.Rows.Add("Grant Allman", "Tiger Woods");
            picks.Rows.Add("Grant Allman", "Zach Johnson");
            picks.Rows.Add("John Alpaugh", "Adam Scott");
            picks.Rows.Add("John Alpaugh", "Bubba Watson");
            picks.Rows.Add("John Alpaugh", "Dustin Johnson");
            picks.Rows.Add("John Alpaugh", "Hunter Mahan");
            picks.Rows.Add("John Alpaugh", "Johnson Wagner");
            picks.Rows.Add("John Alpaugh", "Padraig Harrington");
            picks.Rows.Add("John Alpaugh", "Ricky Barnes");
            picks.Rows.Add("John Alpaugh", "Rory McIlroy");
            picks.Rows.Add("John Alpaugh", "Tiger Woods");
            picks.Rows.Add("John Alpaugh", "Troy Matteson");
            picks.Rows.Add("Neil Heron", "Adam Scott");
            picks.Rows.Add("Neil Heron", "Anthony Kim");
            picks.Rows.Add("Neil Heron", "Bubba Watson");
            picks.Rows.Add("Neil Heron", "Camilo Villegas");
            picks.Rows.Add("Neil Heron", "Geoff Ogilvy");
            picks.Rows.Add("Neil Heron", "Hunter Mahan");
            picks.Rows.Add("Neil Heron", "Ian Poulter");
            picks.Rows.Add("Neil Heron", "Rickie Fowler");
            picks.Rows.Add("Neil Heron", "Rory McIlroy");
            picks.Rows.Add("Neil Heron", "Tiger Woods");
            picks.Rows.Add("Stanley Verch", "Chris Kirk");
            picks.Rows.Add("Stanley Verch", "Jonathan Byrd");
            picks.Rows.Add("Stanley Verch", "Justin Rose");
            picks.Rows.Add("Stanley Verch", "Kris Blanks");
            picks.Rows.Add("Stanley Verch", "Rickie Fowler");
            picks.Rows.Add("Stanley Verch", "Rory McIlroy");
            picks.Rows.Add("Stanley Verch", "Ryan Palmer");
            picks.Rows.Add("Stanley Verch", "Steve Stricker");
            picks.Rows.Add("Stanley Verch", "Tiger Woods");
            picks.Rows.Add("Stanley Verch", "Trevor Immelman");
            picks.Rows.Add("Mike Doller 1", "Adam Scott");
            picks.Rows.Add("Mike Doller 1", "Anthony Kim");
            picks.Rows.Add("Mike Doller 1", "Bud Cauley");
            picks.Rows.Add("Mike Doller 1", "Hunter Mahan");
            picks.Rows.Add("Mike Doller 1", "Jim Furyk");
            picks.Rows.Add("Mike Doller 1", "Keegan Bradley");
            picks.Rows.Add("Mike Doller 1", "Lee Westwood");
            picks.Rows.Add("Mike Doller 1", "Matt Kuchar");
            picks.Rows.Add("Mike Doller 1", "Rory McIlroy");
            picks.Rows.Add("Mike Doller 1", "Tiger Woods");
            picks.Rows.Add("Mike Doller 2", "Adam Scott");
            picks.Rows.Add("Mike Doller 2", "Bubba Watson");
            picks.Rows.Add("Mike Doller 2", "Bud Cauley");
            picks.Rows.Add("Mike Doller 2", "Keegan Bradley");
            picks.Rows.Add("Mike Doller 2", "Lee Westwood");
            picks.Rows.Add("Mike Doller 2", "Matt Kuchar");
            picks.Rows.Add("Mike Doller 2", "Paul Casey");
            picks.Rows.Add("Mike Doller 2", "Rickie Fowler");
            picks.Rows.Add("Mike Doller 2", "Rory McIlroy");
            picks.Rows.Add("Mike Doller 2", "Tiger Woods");
            picks.Rows.Add("Bob A", "Chris Kirk");
            picks.Rows.Add("Bob A", "Dustin Johnson");
            picks.Rows.Add("Bob A", "Jim Furyk");
            picks.Rows.Add("Bob A", "Keegan Bradley");
            picks.Rows.Add("Bob A", "Matt Kuchar");
            picks.Rows.Add("Bob A", "Rory McIlroy");
            picks.Rows.Add("Bob A", "Sang-Moon Bae");
            picks.Rows.Add("Bob A", "Seung-yul Noh");
            picks.Rows.Add("Bob A", "Tiger Woods");
            picks.Rows.Add("Bob A", "Tommy Gainey");
            picks.Rows.Add("Nick Bright", "Charles Howell III");
            picks.Rows.Add("Nick Bright", "Gary Woodland");
            picks.Rows.Add("Nick Bright", "Hunter Mahan");
            picks.Rows.Add("Nick Bright", "Jim Furyk");
            picks.Rows.Add("Nick Bright", "Jonathan Byrd");
            picks.Rows.Add("Nick Bright", "Lee Westwood");
            picks.Rows.Add("Nick Bright", "Rickie Fowler");
            picks.Rows.Add("Nick Bright", "Rory McIlroy");
            picks.Rows.Add("Nick Bright", "Sergio Garcia");
            picks.Rows.Add("Nick Bright", "Tiger Woods");
            picks.Rows.Add("David Taylor 1", "Charles Howell III");
            picks.Rows.Add("David Taylor 1", "J.B. Holmes");
            picks.Rows.Add("David Taylor 1", "Lee Westwood");
            picks.Rows.Add("David Taylor 1", "Luke Donald");
            picks.Rows.Add("David Taylor 1", "Martin Kaymer");
            picks.Rows.Add("David Taylor 1", "Matt Kuchar");
            picks.Rows.Add("David Taylor 1", "Rory McIlroy");
            picks.Rows.Add("David Taylor 1", "Sean O'Hair");
            picks.Rows.Add("David Taylor 1", "Sergio Garcia");
            picks.Rows.Add("David Taylor 1", "Tiger Woods");
            picks.Rows.Add("David Taylor 2", "Bill Haas");
            picks.Rows.Add("David Taylor 2", "Dustin Johnson");
            picks.Rows.Add("David Taylor 2", "Keegan Bradley");
            picks.Rows.Add("David Taylor 2", "Lee Westwood");
            picks.Rows.Add("David Taylor 2", "Martin Kaymer");
            picks.Rows.Add("David Taylor 2", "Rory McIlroy");
            picks.Rows.Add("David Taylor 2", "Sergio Garcia");
            picks.Rows.Add("David Taylor 2", "Spencer Levin");
            picks.Rows.Add("David Taylor 2", "Tiger Woods");
            picks.Rows.Add("David Taylor 2", "Trevor Immelman");
            picks.Rows.Add("Tom O'Gara", "Adam Scott");
            picks.Rows.Add("Tom O'Gara", "Brendan Steele");
            picks.Rows.Add("Tom O'Gara", "Geoff Ogilvy");
            picks.Rows.Add("Tom O'Gara", "Ian Poulter");
            picks.Rows.Add("Tom O'Gara", "Jhonattan Vegas");
            picks.Rows.Add("Tom O'Gara", "Keegan Bradley");
            picks.Rows.Add("Tom O'Gara", "Kevin Streelman");
            picks.Rows.Add("Tom O'Gara", "Rickie Fowler");
            picks.Rows.Add("Tom O'Gara", "Tiger Woods");
            picks.Rows.Add("Tom O'Gara", "Zach Johnson");
            picks.Rows.Add("Chris Head", "Adam Scott");
            picks.Rows.Add("Chris Head", "Hunter Mahan");
            picks.Rows.Add("Chris Head", "Jason Day");
            picks.Rows.Add("Chris Head", "Jim Furyk");
            picks.Rows.Add("Chris Head", "Justin Leonard");
            picks.Rows.Add("Chris Head", "Lee Westwood");
            picks.Rows.Add("Chris Head", "Martin Kaymer");
            picks.Rows.Add("Chris Head", "Matt Kuchar");
            picks.Rows.Add("Chris Head", "Rory McIlroy");
            picks.Rows.Add("Chris Head", "Tiger Woods");
            picks.Rows.Add("Paul Cusack", "Aaron Baddeley");
            picks.Rows.Add("Paul Cusack", "Alvaro Quiros");
            picks.Rows.Add("Paul Cusack", "Fredrik Jacobson");
            picks.Rows.Add("Paul Cusack", "Jason Day");
            picks.Rows.Add("Paul Cusack", "Jonathan Byrd");
            picks.Rows.Add("Paul Cusack", "Justin Rose");
            picks.Rows.Add("Paul Cusack", "Lee Westwood");
            picks.Rows.Add("Paul Cusack", "Martin Kaymer");
            picks.Rows.Add("Paul Cusack", "Rickie Fowler");
            picks.Rows.Add("Paul Cusack", "Tiger Woods");
            picks.Rows.Add("Hugh Lynar", "Angel Cabrera");
            picks.Rows.Add("Hugh Lynar", "Jason Day");
            picks.Rows.Add("Hugh Lynar", "Jhonattan Vegas");
            picks.Rows.Add("Hugh Lynar", "K.J. Choi");
            picks.Rows.Add("Hugh Lynar", "Keegan Bradley");
            picks.Rows.Add("Hugh Lynar", "Rickie Fowler");
            picks.Rows.Add("Hugh Lynar", "Rory McIlroy");
            picks.Rows.Add("Hugh Lynar", "Stuart Appleby");
            picks.Rows.Add("Hugh Lynar", "Tiger Woods");
            picks.Rows.Add("Hugh Lynar", "Zach Johnson");
            picks.Rows.Add("Team June", "Charl Schwartzel");
            picks.Rows.Add("Team June", "Charlie Wi");
            picks.Rows.Add("Team June", "Chris Couch");
            picks.Rows.Add("Team June", "Dustin Johnson");
            picks.Rows.Add("Team June", "Graeme McDowell");
            picks.Rows.Add("Team June", "Harrison Fraser");
            picks.Rows.Add("Team June", "Jim Furyk");
            picks.Rows.Add("Team June", "Rickie Fowler");
            picks.Rows.Add("Team June", "Ricky Barnes");
            picks.Rows.Add("Team June", "Steve Stricker");
            picks.Rows.Add("Mark 1", "Camilo Villegas");
            picks.Rows.Add("Mark 1", "Dustin Johnson");
            picks.Rows.Add("Mark 1", "Jim Furyk");
            picks.Rows.Add("Mark 1", "John Rollins");
            picks.Rows.Add("Mark 1", "Nick Watney");
            picks.Rows.Add("Mark 1", "Robert Allenby");
            picks.Rows.Add("Mark 1", "Sergio Garcia");
            picks.Rows.Add("Mark 1", "Tiger Woods");
            picks.Rows.Add("Mark 1", "Tim Herron");
            picks.Rows.Add("Mark 1", "Zach Johnson");
            picks.Rows.Add("Mark 2 ", "Brendon de Jonge");
            picks.Rows.Add("Mark 2 ", "Camilo Villegas");
            picks.Rows.Add("Mark 2 ", "Charles Howell III");
            picks.Rows.Add("Mark 2 ", "Dustin Johnson");
            picks.Rows.Add("Mark 2 ", "Jim Furyk");
            picks.Rows.Add("Mark 2 ", "John Rollins");
            picks.Rows.Add("Mark 2 ", "Kyle Stanley");
            picks.Rows.Add("Mark 2 ", "Matt Kuchar");
            picks.Rows.Add("Mark 2 ", "Sergio Garcia");
            picks.Rows.Add("Mark 2 ", "Tiger Woods");
            picks.Rows.Add("Laura V", "Brendan Steele");
            picks.Rows.Add("Laura V", "Chris DiMarco");
            picks.Rows.Add("Laura V", "Heath Slocum");
            picks.Rows.Add("Laura V", "Hunter Mahan");
            picks.Rows.Add("Laura V", "Jim Furyk");
            picks.Rows.Add("Laura V", "Keegan Bradley");
            picks.Rows.Add("Laura V", "Matt Kuchar");
            picks.Rows.Add("Laura V", "Robert Allenby");
            picks.Rows.Add("Laura V", "Sean O'Hair");
            picks.Rows.Add("Laura V", "Tiger Woods");
            picks.Rows.Add("Jean Hamilton", "Anthony Kim");
            picks.Rows.Add("Jean Hamilton", "Ernie Els");
            picks.Rows.Add("Jean Hamilton", "Graeme McDowell");
            picks.Rows.Add("Jean Hamilton", "Ian Poulter");
            picks.Rows.Add("Jean Hamilton", "Lee Westwood");
            picks.Rows.Add("Jean Hamilton", "Luke Donald");
            picks.Rows.Add("Jean Hamilton", "Martin Laird");
            picks.Rows.Add("Jean Hamilton", "Matt Kuchar");
            picks.Rows.Add("Jean Hamilton", "Rory McIlroy");
            picks.Rows.Add("Jean Hamilton", "Tiger Woods");
            picks.Rows.Add("John Welsh", "Anthony Kim");
            picks.Rows.Add("John Welsh", "Charl Schwartzel");
            picks.Rows.Add("John Welsh", "Gary Woodland");
            picks.Rows.Add("John Welsh", "Hunter Haas");
            picks.Rows.Add("John Welsh", "Lee Westwood");
            picks.Rows.Add("John Welsh", "Martin Laird");
            picks.Rows.Add("John Welsh", "Michael Bradley");
            picks.Rows.Add("John Welsh", "Rory McIlroy");
            picks.Rows.Add("John Welsh", "Tiger Woods");
            picks.Rows.Add("John Welsh", "Webb Simpson");
            picks.Rows.Add("Matt Simpson", "Bo Van Pelt");
            picks.Rows.Add("Matt Simpson", "Bryce Molder");
            picks.Rows.Add("Matt Simpson", "Charles Howell III");
            picks.Rows.Add("Matt Simpson", "Geoff Ogilvy");
            picks.Rows.Add("Matt Simpson", "Jason Day");
            picks.Rows.Add("Matt Simpson", "Rickie Fowler");
            picks.Rows.Add("Matt Simpson", "Rory McIlroy");
            picks.Rows.Add("Matt Simpson", "Sergio Garcia");
            picks.Rows.Add("Matt Simpson", "Tiger Woods");
            picks.Rows.Add("Matt Simpson", "Zach Johnson");
            picks.Rows.Add("David Simpson", "Adam Scott");
            picks.Rows.Add("David Simpson", "Carl Pettersson");
            picks.Rows.Add("David Simpson", "Geoff Ogilvy");
            picks.Rows.Add("David Simpson", "Hunter Mahan");
            picks.Rows.Add("David Simpson", "Jason Day");
            picks.Rows.Add("David Simpson", "Lee Westwood");
            picks.Rows.Add("David Simpson", "Rickie Fowler");
            picks.Rows.Add("David Simpson", "Rory McIlroy");
            picks.Rows.Add("David Simpson", "Sergio Garcia");
            picks.Rows.Add("David Simpson", "Tiger Woods");
            picks.Rows.Add("Tyler Simpson", "Brendon de Jonge");
            picks.Rows.Add("Tyler Simpson", "Cameron Tringale");
            picks.Rows.Add("Tyler Simpson", "Charlie Wi");
            picks.Rows.Add("Tyler Simpson", "Geoff Ogilvy");
            picks.Rows.Add("Tyler Simpson", "Hunter Mahan");
            picks.Rows.Add("Tyler Simpson", "Jhonattan Vegas");
            picks.Rows.Add("Tyler Simpson", "Phil Mickelson");
            picks.Rows.Add("Tyler Simpson", "Rickie Fowler");
            picks.Rows.Add("Tyler Simpson", "Robert Karlsson");
            picks.Rows.Add("Tyler Simpson", "Trevor Immelman");
            picks.Rows.Add("David Moore", "Adam Scott");
            picks.Rows.Add("David Moore", "Brian Gay");
            picks.Rows.Add("David Moore", "Geoff Ogilvy");
            picks.Rows.Add("David Moore", "Hunter Mahan");
            picks.Rows.Add("David Moore", "Jim Furyk");
            picks.Rows.Add("David Moore", "Keegan Bradley");
            picks.Rows.Add("David Moore", "Rickie Fowler");
            picks.Rows.Add("David Moore", "Ricky Barnes");
            picks.Rows.Add("David Moore", "Rory McIlroy");
            picks.Rows.Add("David Moore", "Tiger Woods");
        }

        public DataTable getPicks()
        {
            return picks;
        }

    }
}
